/*-*- mode:c;indent-tabs-mode:nil;c-basic-offset:2;tab-width:8;coding:utf-8 -*-│
│ vi: set et ft=c ts=2 sts=2 sw=2 fenc=utf-8                               :vi │
╞══════════════════════════════════════════════════════════════════════════════╡
│ Copyright 2026 Justine Alexandra Roberts Tunney                              │
│                                                                              │
│ Permission to use, copy, modify, and/or distribute this software for         │
│ any purpose with or without fee is hereby granted, provided that the         │
│ above copyright notice and this permission notice appear in all copies.      │
│                                                                              │
│ THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL                │
│ WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED                │
│ WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE             │
│ AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL         │
│ DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR        │
│ PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER               │
│ TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR             │
│ PERFORMANCE OF THIS SOFTWARE.                                                │
╚─────────────────────────────────────────────────────────────────────────────*/
#include "libc/dce.h"
#include "libc/sysv/consts/fio.h"
#include "libc/sysv/consts/iff.h"
#include "libc/sysv/consts/sio.h"

#define ACTUAL2DEF(X) \
  if (actual == X##_) \
    return X;

#define DEF2ACTUAL(X) \
  if (request == X)   \
    return X##_;

/**
 * Translates compile-time ioctl requests to host OS value.
 *
 * Unknown requests pass through unchanged, so we don't drop user
 * input; unknown values are best reported by the host OS itself.
 */
pureconst int __linux2ioctl(const unsigned long request) {
  DEF2ACTUAL(FIONREAD);
  DEF2ACTUAL(FIONBIO);
  DEF2ACTUAL(FIOCLEX);
  DEF2ACTUAL(FIONCLEX);
  DEF2ACTUAL(FIOASYNC);
  DEF2ACTUAL(SIOCGIFCONF);
  DEF2ACTUAL(SIOCGIFADDR);
  DEF2ACTUAL(SIOCSIFADDR);
  DEF2ACTUAL(SIOCDIFADDR);
  DEF2ACTUAL(SIOCGIFBRDADDR);
  DEF2ACTUAL(SIOCSIFBRDADDR);
  DEF2ACTUAL(SIOCGIFNETMASK);
  DEF2ACTUAL(SIOCSIFNETMASK);
  DEF2ACTUAL(SIOCGIFFLAGS);
  DEF2ACTUAL(SIOCSIFFLAGS);
  DEF2ACTUAL(SIOCGIFMETRIC);
  DEF2ACTUAL(SIOCSIFMETRIC);
  DEF2ACTUAL(SIOCGIFDSTADDR);
  DEF2ACTUAL(SIOCSIFDSTADDR);
  DEF2ACTUAL(SIOCGIFMTU);
  DEF2ACTUAL(SIOCSIFMTU);
  DEF2ACTUAL(SIOCGPGRP);
  DEF2ACTUAL(SIOCSPGRP);
  DEF2ACTUAL(SIOCADDMULTI);
  DEF2ACTUAL(SIOCDELMULTI);
  DEF2ACTUAL(SIOCGIFINDEX);
  DEF2ACTUAL(SIOCSIFNAME);
  DEF2ACTUAL(SIOCADDDLCI);
  DEF2ACTUAL(SIOCADDRT);
  DEF2ACTUAL(SIOCDARP);
  DEF2ACTUAL(SIOCDELDLCI);
  DEF2ACTUAL(SIOCDELRT);
  DEF2ACTUAL(SIOCDEVPRIVATE);
  DEF2ACTUAL(SIOCDRARP);
  DEF2ACTUAL(SIOCGARP);
  DEF2ACTUAL(SIOCGIFBR);
  DEF2ACTUAL(SIOCGIFCOUNT);
  DEF2ACTUAL(SIOCGIFENCAP);
  DEF2ACTUAL(SIOCGIFHWADDR);
  DEF2ACTUAL(SIOCGIFMAP);
  DEF2ACTUAL(SIOCGIFMEM);
  DEF2ACTUAL(SIOCGIFNAME);
  DEF2ACTUAL(SIOCGIFPFLAGS);
  DEF2ACTUAL(SIOCGIFSLAVE);
  DEF2ACTUAL(SIOCGIFTXQLEN);
  DEF2ACTUAL(SIOCGRARP);
  DEF2ACTUAL(SIOCGSTAMP);
  DEF2ACTUAL(SIOCGSTAMPNS);
  DEF2ACTUAL(SIOCPROTOPRIVATE);
  DEF2ACTUAL(SIOCRTMSG);
  DEF2ACTUAL(SIOCSARP);
  DEF2ACTUAL(SIOCSIFBR);
  DEF2ACTUAL(SIOCSIFENCAP);
  DEF2ACTUAL(SIOCSIFHWADDR);
  DEF2ACTUAL(SIOCSIFHWBROADCAST);
  DEF2ACTUAL(SIOCSIFLINK);
  DEF2ACTUAL(SIOCSIFMAP);
  DEF2ACTUAL(SIOCSIFMEM);
  DEF2ACTUAL(SIOCSIFPFLAGS);
  DEF2ACTUAL(SIOCSIFSLAVE);
  DEF2ACTUAL(SIOCSIFTXQLEN);
  DEF2ACTUAL(SIOCSRARP);
  DEF2ACTUAL(SIOGIFINDEX);
  return request;
}

/**
 * Translates host OS ioctl requests to compile-time value.
 */
pureconst int __ioctl2linux(const unsigned long actual) {
  ACTUAL2DEF(FIONREAD);
  ACTUAL2DEF(FIONBIO);
  ACTUAL2DEF(FIOCLEX);
  ACTUAL2DEF(FIONCLEX);
  ACTUAL2DEF(FIOASYNC);
  ACTUAL2DEF(SIOCGIFCONF);
  ACTUAL2DEF(SIOCGIFADDR);
  ACTUAL2DEF(SIOCSIFADDR);
  ACTUAL2DEF(SIOCDIFADDR);
  ACTUAL2DEF(SIOCGIFBRDADDR);
  ACTUAL2DEF(SIOCSIFBRDADDR);
  ACTUAL2DEF(SIOCGIFNETMASK);
  ACTUAL2DEF(SIOCSIFNETMASK);
  ACTUAL2DEF(SIOCGIFFLAGS);
  ACTUAL2DEF(SIOCSIFFLAGS);
  ACTUAL2DEF(SIOCGIFMETRIC);
  ACTUAL2DEF(SIOCSIFMETRIC);
  ACTUAL2DEF(SIOCGIFDSTADDR);
  ACTUAL2DEF(SIOCSIFDSTADDR);
  ACTUAL2DEF(SIOCGIFMTU);
  ACTUAL2DEF(SIOCSIFMTU);
  ACTUAL2DEF(SIOCGPGRP);
  ACTUAL2DEF(SIOCSPGRP);
  ACTUAL2DEF(SIOCADDMULTI);
  ACTUAL2DEF(SIOCDELMULTI);
  ACTUAL2DEF(SIOCGIFINDEX);
  ACTUAL2DEF(SIOCSIFNAME);
  ACTUAL2DEF(SIOCADDDLCI);
  ACTUAL2DEF(SIOCADDRT);
  ACTUAL2DEF(SIOCDARP);
  ACTUAL2DEF(SIOCDELDLCI);
  ACTUAL2DEF(SIOCDELRT);
  ACTUAL2DEF(SIOCDEVPRIVATE);
  ACTUAL2DEF(SIOCDRARP);
  ACTUAL2DEF(SIOCGARP);
  ACTUAL2DEF(SIOCGIFBR);
  ACTUAL2DEF(SIOCGIFCOUNT);
  ACTUAL2DEF(SIOCGIFENCAP);
  ACTUAL2DEF(SIOCGIFHWADDR);
  ACTUAL2DEF(SIOCGIFMAP);
  ACTUAL2DEF(SIOCGIFMEM);
  ACTUAL2DEF(SIOCGIFNAME);
  ACTUAL2DEF(SIOCGIFPFLAGS);
  ACTUAL2DEF(SIOCGIFSLAVE);
  ACTUAL2DEF(SIOCGIFTXQLEN);
  ACTUAL2DEF(SIOCGRARP);
  ACTUAL2DEF(SIOCGSTAMP);
  ACTUAL2DEF(SIOCGSTAMPNS);
  ACTUAL2DEF(SIOCPROTOPRIVATE);
  ACTUAL2DEF(SIOCRTMSG);
  ACTUAL2DEF(SIOCSARP);
  ACTUAL2DEF(SIOCSIFBR);
  ACTUAL2DEF(SIOCSIFENCAP);
  ACTUAL2DEF(SIOCSIFHWADDR);
  ACTUAL2DEF(SIOCSIFHWBROADCAST);
  ACTUAL2DEF(SIOCSIFLINK);
  ACTUAL2DEF(SIOCSIFMAP);
  ACTUAL2DEF(SIOCSIFMEM);
  ACTUAL2DEF(SIOCSIFPFLAGS);
  ACTUAL2DEF(SIOCSIFSLAVE);
  ACTUAL2DEF(SIOCSIFTXQLEN);
  ACTUAL2DEF(SIOCSRARP);
  ACTUAL2DEF(SIOGIFINDEX);
  return actual;
}

#define IFFACTUAL2DEF(X, A) \
  if (flags & A)            \
    r |= X;

#define IFFDEF2ACTUAL(X, A) \
  if (flags & X)            \
    r |= A;

/**
 * Translates host OS interface flags to compile-time value.
 *
 * Most IFF_ bits are consensus; the bsd encoding differs for
 * IFF_MULTICAST, and windows differs for IFF_LOOPBACK. Bits that
 * an operating system doesn't support can never be reported.
 */
const int __iflag2linux(const int flags) {
  int r = 0;
  if (IsWindows()) {
    IFFACTUAL2DEF(IFF_UP, IFF_UP);
    IFFACTUAL2DEF(IFF_BROADCAST, IFF_BROADCAST);
    IFFACTUAL2DEF(IFF_DEBUG, IFF_DEBUG);
    IFFACTUAL2DEF(IFF_LOOPBACK, 4); /* nt magic */
    IFFACTUAL2DEF(IFF_POINTOPOINT, IFF_POINTOPOINT);
    IFFACTUAL2DEF(IFF_NOARP, IFF_NOARP);
    IFFACTUAL2DEF(IFF_ALLMULTI, IFF_ALLMULTI);
    IFFACTUAL2DEF(IFF_MULTICAST, IFF_MULTICAST);
    IFFACTUAL2DEF(IFF_PROMISC, IFF_PROMISC);
  } else if (!IsLinux()) {
    IFFACTUAL2DEF(IFF_UP, IFF_UP);
    IFFACTUAL2DEF(IFF_BROADCAST, IFF_BROADCAST);
    IFFACTUAL2DEF(IFF_DEBUG, IFF_DEBUG);
    IFFACTUAL2DEF(IFF_LOOPBACK, IFF_LOOPBACK);
    IFFACTUAL2DEF(IFF_POINTOPOINT, IFF_POINTOPOINT);
    IFFACTUAL2DEF(IFF_NOTRAILERS, IFF_NOTRAILERS);
    IFFACTUAL2DEF(IFF_RUNNING, IFF_RUNNING);
    IFFACTUAL2DEF(IFF_NOARP, IFF_NOARP);
    IFFACTUAL2DEF(IFF_ALLMULTI, IFF_ALLMULTI);
    IFFACTUAL2DEF(IFF_MASTER, IFF_MASTER);
    IFFACTUAL2DEF(IFF_SLAVE, IFF_SLAVE);
    IFFACTUAL2DEF(IFF_MULTICAST, 0x8000); /* bsd magic */
    IFFACTUAL2DEF(IFF_PROMISC, IFF_PROMISC);
  } else {
    r = flags;
  }
  return r;
}

/**
 * Translates compile-time interface flags to host OS value.
 */
const int __linux2iflag(const int flags) {
  int r = 0;
  if (IsWindows()) {
    IFFDEF2ACTUAL(IFF_UP, IFF_UP);
    IFFDEF2ACTUAL(IFF_BROADCAST, IFF_BROADCAST);
    IFFDEF2ACTUAL(IFF_DEBUG, IFF_DEBUG);
    IFFDEF2ACTUAL(IFF_LOOPBACK, 4); /* nt magic */
    IFFDEF2ACTUAL(IFF_POINTOPOINT, IFF_POINTOPOINT);
    IFFDEF2ACTUAL(IFF_NOARP, IFF_NOARP);
    IFFDEF2ACTUAL(IFF_ALLMULTI, IFF_ALLMULTI);
    IFFDEF2ACTUAL(IFF_MULTICAST, IFF_MULTICAST);
    IFFDEF2ACTUAL(IFF_PROMISC, IFF_PROMISC);
  } else if (!IsLinux()) {
    IFFDEF2ACTUAL(IFF_UP, IFF_UP);
    IFFDEF2ACTUAL(IFF_BROADCAST, IFF_BROADCAST);
    IFFDEF2ACTUAL(IFF_DEBUG, IFF_DEBUG);
    IFFDEF2ACTUAL(IFF_LOOPBACK, IFF_LOOPBACK);
    IFFDEF2ACTUAL(IFF_POINTOPOINT, IFF_POINTOPOINT);
    IFFDEF2ACTUAL(IFF_NOTRAILERS, IFF_NOTRAILERS);
    IFFDEF2ACTUAL(IFF_RUNNING, IFF_RUNNING);
    IFFDEF2ACTUAL(IFF_NOARP, IFF_NOARP);
    IFFDEF2ACTUAL(IFF_ALLMULTI, IFF_ALLMULTI);
    IFFDEF2ACTUAL(IFF_MASTER, IFF_MASTER);
    IFFDEF2ACTUAL(IFF_SLAVE, IFF_SLAVE);
    IFFDEF2ACTUAL(IFF_MULTICAST, 0x8000); /* bsd magic */
    IFFDEF2ACTUAL(IFF_PROMISC, IFF_PROMISC);
  } else {
    r = flags;
  }
  return r;
}
