#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_CLOSE_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_CLOSE_H_
COSMOPOLITAN_C_START_

extern const unsigned int CLOSE_RANGE_CLOEXEC_;
extern const unsigned int CLOSE_RANGE_UNSHARE_;

COSMOPOLITAN_C_END_

#define CLOSE_RANGE_CLOEXEC  4 /* picking linux values as default */
#define CLOSE_RANGE_UNSHARE  2

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_CLOSE_H_ */
