#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_EXIT_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_EXIT_H_

#ifndef EXIT_SUCCESS
#define EXIT_SUCCESS 0
#endif

#ifndef EXIT_FAILURE
#define EXIT_FAILURE 1
#endif


#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_EXIT_H_ */
