#ifndef COSMOPOLITAN_LIBC_SYSV_CONSTS_UNMOUNT_H_
#define COSMOPOLITAN_LIBC_SYSV_CONSTS_UNMOUNT_H_
COSMOPOLITAN_C_START_

extern const int MNT_FORCE_;
extern const int MNT_DETACH_;
extern const int MNT_EXPIRE_;
extern const int UMOUNT_NOFOLLOW_;
extern const int MNT_BYFSID;

COSMOPOLITAN_C_END_

#define MNT_FORCE       0x00000001
#define MNT_DETACH      0x00000002
#define MNT_EXPIRE      0x00000004
#define UMOUNT_NOFOLLOW 0x00000008

#endif /* COSMOPOLITAN_LIBC_SYSV_CONSTS_UNMOUNT_H_ */
